// The built-in Word Search themes, written for this firmware. Titles and words are English
// content (like the Quote card's quotes), not UI strings, so they are not translated. Every
// list is general and family-friendly: no brand or franchise names, no real people.
//
// Each list is one "WORD|WORD|..." string in flash. The tests check every word against the
// theme-file rules (normalizeWordLine), at least 30 words a theme, no duplicates, and that
// every theme fills Easy, Medium and Hard and fits the screen's word list.

#include <cstring>

#include "WsThemes.h"

namespace ws {

namespace {

constexpr BuiltinTheme THEMES[] = {
    {"animals", "Animals",
     "LION|TIGER|ZEBRA|GIRAFFE|ELEPHANT|MONKEY|KANGAROO|KOALA|PANDA|RHINO|HIPPO|CAMEL|LLAMA|BEAVER|OTTER|"
     "RABBIT|SQUIRREL|CHIPMUNK|RACCOON|BADGER|MOOSE|BISON|WOLF|FOX|BEAR|DEER|GOAT|SHEEP|HORSE|DONKEY|MOUSE|"
     "HEDGEHOG|ARMADILLO|CHEETAH|LEOPARD|GORILLA|YAK|LYNX|SKUNK|PORCUPINE"},
    {"birds", "Birds",
     "ROBIN|SPARROW|EAGLE|HAWK|FALCON|OWL|CROW|RAVEN|PIGEON|DOVE|PARROT|PENGUIN|PELICAN|HERON|CRANE|STORK|"
     "FLAMINGO|SWAN|GOOSE|DUCK|FINCH|WREN|CARDINAL|BLUE JAY|MAGPIE|WOODPECKER|HUMMINGBIRD|KINGFISHER|OSPREY|"
     "PUFFIN|TOUCAN|OSTRICH|EMU|KIWI|LARK|QUAIL|CHICKADEE|NUTHATCH|SANDPIPER"},
    {"ocean", "Ocean Life",
     "WHALE|DOLPHIN|SHARK|OCTOPUS|SQUID|JELLYFISH|STARFISH|SEAHORSE|CRAB|LOBSTER|SHRIMP|CLAM|OYSTER|MUSSEL|"
     "SCALLOP|CORAL|SPONGE|URCHIN|EEL|RAY|TUNA|MARLIN|SWORDFISH|ORCA|SEAL|WALRUS|SEA OTTER|MANATEE|TURTLE|"
     "PLANKTON|KELP|ANEMONE|BARNACLE|NARWHAL|PUFFERFISH|CUTTLEFISH|KRILL|HALIBUT"},
    {"insects", "Insects",
     "ANTS|HONEYBEE|BUMBLEBEE|WASP|HORNET|BEETLE|LADYBUG|BUTTERFLY|MOTH|DRAGONFLY|GRASSHOPPER|CRICKET|"
     "CICADA|TERMITE|FLEA|MOSQUITO|FIREFLY|MANTIS|APHID|WEEVIL|EARWIG|LOCUST|KATYDID|GNAT|HOUSEFLY|"
     "SILVERFISH|STICK INSECT|CATERPILLAR|LARVA|COCOON|ANTENNA|THORAX|ABDOMEN|WINGS"},
    {"trees", "Trees",
     "OAK|MAPLE|BIRCH|PINE|SPRUCE|FIR|CEDAR|ASPEN|WILLOW|ELM|ASH|BEECH|HICKORY|WALNUT|CHESTNUT|POPLAR|"
     "SYCAMORE|MAGNOLIA|DOGWOOD|REDWOOD|SEQUOIA|CYPRESS|JUNIPER|HEMLOCK|LARCH|ALDER|BAOBAB|PALM|BANYAN|"
     "EUCALYPTUS|OLIVE|CHERRY|LINDEN|HAWTHORN|YEW|ACORN|BARK|ROOTS"},
    {"flowers", "Flowers",
     "ROSE|TULIP|DAISY|LILY|ORCHID|SUNFLOWER|DAFFODIL|IRIS|VIOLET|POPPY|LAVENDER|MARIGOLD|PEONY|CARNATION|"
     "LILAC|JASMINE|HIBISCUS|GERANIUM|PANSY|PETUNIA|ZINNIA|DAHLIA|ASTER|CROCUS|HYACINTH|BLUEBELL|BUTTERCUP|"
     "CLOVER|LOTUS|GARDENIA|SNAPDRAGON|FOXGLOVE|BEGONIA|SNOWDROP|HONEYSUCKLE"},
    {"fruit", "Fruit",
     "APPLE|BANANA|ORANGE|GRAPES|CHERRY|PEACH|PEAR|PLUM|MANGO|PAPAYA|PINEAPPLE|KIWI|LEMON|LIME|HONEYDEW|"
     "WATERMELON|STRAWBERRY|BLUEBERRY|RASPBERRY|BLACKBERRY|APRICOT|COCONUT|FIG|DATE|GUAVA|LYCHEE|"
     "POMEGRANATE|TANGERINE|GRAPEFRUIT|CRANBERRY|NECTARINE|QUINCE|PERSIMMON|CANTALOUPE"},
    {"vegetables", "Vegetables",
     "CARROT|POTATO|TOMATO|ONION|GARLIC|LETTUCE|SPINACH|CABBAGE|BROCCOLI|CAULIFLOWER|CELERY|CUCUMBER|PEPPER|"
     "CORN|PEAS|BEANS|BEET|RADISH|TURNIP|PARSNIP|SQUASH|PUMPKIN|ZUCCHINI|EGGPLANT|ASPARAGUS|ARTICHOKE|KALE|"
     "LEEK|OKRA|YAM|SHALLOT|CHARD|SPROUTS|RHUBARB|GINGER|ENDIVE|ARUGULA"},
    {"weather", "Weather",
     "RAINFALL|SNOWDRIFT|SLEET|HAIL|FOG|MIST|CLOUD|THUNDER|LIGHTNING|STORM|WIND|BREEZE|GUST|TORNADO|"
     "HURRICANE|BLIZZARD|DRIZZLE|SHOWER|RAINBOW|SUNSHINE|HUMIDITY|FROST|DEW|DROUGHT|HEAT WAVE|FORECAST|"
     "BAROMETER|PRESSURE|TEMPERATURE|MONSOON|CYCLONE|SQUALL|OVERCAST|SNOWFLAKE|ICICLE"},
    {"space", "Space",
     "PLANET|STAR|COMET|ASTEROID|METEOR|GALAXY|NEBULA|ORBIT|MOON|SUN|MERCURY|VENUS|EARTH|MARS|JUPITER|"
     "SATURN|NEPTUNE|PLUTO|ROCKET|ASTRONAUT|TELESCOPE|SATELLITE|ECLIPSE|GRAVITY|COSMOS|SUPERNOVA|QUASAR|"
     "PULSAR|BLACK HOLE|CONSTELLATION|LUNAR|SOLAR|CRATER|SPACESHIP|ROVER|LIGHT YEAR"},
    {"camping", "Camping",
     "TENT|CAMPFIRE|SLEEPING BAG|LANTERN|FLASHLIGHT|COMPASS|MAP|BACKPACK|CANTEEN|TRAIL|HIKE|CABIN|FOREST|"
     "LAKE|MARSHMALLOW|S'MORES|KINDLING|FIREWOOD|MATCHES|HATCHET|COOLER|STOVE|PICNIC|TARP|ROPE|KNOT|"
     "BLANKET|PILLOW|CAMPSITE|RANGER|BINOCULARS|WILDLIFE|STARS|CANOE|KAYAK|PADDLE|BUG SPRAY|SUNSCREEN"},
    {"fishing", "Fishing",
     "ROD|REEL|LINE|HOOK|BAIT|LURE|BOBBER|SINKER|NET|TACKLE|WADERS|TROUT|SALMON|BASS|PERCH|PIKE|CATFISH|"
     "WALLEYE|CARP|MINNOW|WORM|CAST|CATCH|RELEASE|BOAT|DOCK|PIER|RIVER|STREAM|CREEK|POND|SPINNER|JIG|"
     "LEADER|TIPPET|SWIVEL|FLOAT|RIFFLE"},
    {"tracking", "Hunting & Tracking",
     "TRACKS|FOOTPRINT|PAW PRINT|HOOF|ANTLER|TRAIL|BLIND|CAMOUFLAGE|BINOCULARS|SCOPE|DECOY|CALL|WHISTLE|"
     "BOOTS|COMPASS|ORANGE VEST|DAWN|DUSK|RIDGE|MEADOW|THICKET|BRUSH|BURROW|DEN|NEST|BUCK|DOE|FAWN|ELK|"
     "GROUSE|PHEASANT|TURKEY|HARE|SCENT|STALK|PATIENCE|LICENSE|ARROW|QUIVER|SIGN"},
    {"mountains", "Mountains & Rivers",
     "PEAK|SUMMIT|RIDGE|VALLEY|CANYON|GORGE|CLIFF|BLUFF|SLOPE|GLACIER|CREVASSE|AVALANCHE|BOULDER|PASS|"
     "PLATEAU|MESA|BUTTE|VOLCANO|FOOTHILLS|ALPINE|TIMBERLINE|RIVER|STREAM|BROOK|CREEK|RAPIDS|WATERFALL|"
     "DELTA|MOUTH|BANK|CURRENT|TRIBUTARY|ESTUARY|OXBOW|SPRING|HEADWATERS|MEANDER|FLOODPLAIN"},
    {"kitchen", "Kitchen",
     "SPOON|FORK|KNIFE|LADLE|WHISK|SPATULA|TONGS|SAUCEPAN|STOCKPOT|SKILLET|KETTLE|TEAPOT|OVEN|STOVE|"
     "TOASTER|BLENDER|MIXER|COLANDER|GRATER|PEELER|CUTTING BOARD|APRON|POT HOLDER|PLATE|BOWL|TEACUP|MUG|"
     "GLASS|NAPKIN|SINK|FAUCET|PANTRY|FRIDGE|FREEZER|MICROWAVE|DISHWASHER|TIMER|CUPBOARD"},
    {"baking", "Baking",
     "FLOUR|SUGAR|BUTTER|EGGS|YEAST|DOUGH|BATTER|OVEN|ROLLING PIN|WHISK|MIXING BOWL|MUFFIN|CUPCAKE|"
     "COOKIE|BROWNIE|BREAD|BAGEL|PRETZEL|CROISSANT|PIE CRUST|TART|SCONE|BISCUIT|CINNAMON|VANILLA|NUTMEG|"
     "FROSTING|SPRINKLES|KNEAD|PROOF|BAKING SODA|LAYER CAKE|PASTRY|CRUMB|SHORTBREAD"},
    {"sports", "Sports",
     "SOCCER|BASEBALL|BASKETBALL|FOOTBALL|TENNIS|GOLF|HOCKEY|RUGBY|CRICKET|VOLLEYBALL|BADMINTON|SWIMMING|"
     "DIVING|ROWING|SAILING|SKIING|SNOWBOARD|SKATING|CYCLING|RUNNING|ARCHERY|FENCING|BOXING|WRESTLING|"
     "GYMNASTICS|KARATE|JUDO|BOWLING|CURLING|LACROSSE|SURFING|CLIMBING|TRIATHLON|MARATHON|SOFTBALL|POLO"},
    {"music", "Music",
     "PIANO|GUITAR|VIOLIN|CELLO|FLUTE|CLARINET|TRUMPET|TROMBONE|TUBA|DRUMS|HARP|BANJO|UKULELE|ACCORDION|"
     "HARMONICA|SAXOPHONE|OBOE|BASSOON|XYLOPHONE|TAMBOURINE|MELODY|HARMONY|RHYTHM|TEMPO|CHORD|NOTE|SCALE|"
     "TUNE|SONG|CHOIR|ORCHESTRA|CONCERT|LYRICS|BEAT|TREBLE|OCTAVE|METRONOME"},
    {"colors", "Colors",
     "RED|ORANGE|YELLOW|GREEN|BLUE|PURPLE|PINK|BROWN|BLACK|WHITE|GRAY|SILVER|GOLD|BEIGE|CRIMSON|SCARLET|"
     "MAROON|CORAL|PEACH|AMBER|LIME|OLIVE|TEAL|TURQUOISE|NAVY|INDIGO|VIOLET|LAVENDER|MAGENTA|IVORY|"
     "CHARCOAL|TAN|CREAM|MINT|RUST|BRONZE|EMERALD|SAPPHIRE"},
    {"countries", "Countries",
     "CANADA|MEXICO|BRAZIL|PERU|CHILE|ARGENTINA|COLOMBIA|FRANCE|SPAIN|ITALY|GERMANY|NORWAY|SWEDEN|FINLAND|"
     "IRELAND|POLAND|GREECE|EGYPT|KENYA|MOROCCO|NIGERIA|GHANA|INDIA|CHINA|JAPAN|NEPAL|VIETNAM|THAILAND|"
     "AUSTRALIA|NEW ZEALAND|ICELAND|PORTUGAL|CUBA|JAMAICA|MONGOLIA|ETHIOPIA|AUSTRIA"},
    {"body", "Human Body",
     "HEART|LUNGS|BRAIN|LIVER|KIDNEY|STOMACH|SKELETON|MUSCLE|BONE|SKIN|BLOOD|NERVE|SPINE|SKULL|RIBS|ELBOW|"
     "KNEE|ANKLE|WRIST|SHOULDER|FINGER|THUMB|TOE|HEEL|CHIN|CHEEK|EYEBROW|EYELASH|NOSTRIL|TONGUE|TEETH|JAW|"
     "NECK|HIP|THROAT|PALM|KNUCKLE|FOREHEAD"},
    {"tools", "Tools",
     "HAMMER|SCREWDRIVER|WRENCH|PLIERS|SAW|DRILL|CHISEL|FILE|CLAMP|VISE|LEVEL|TAPE MEASURE|SANDPAPER|MALLET|"
     "CROWBAR|SHOVEL|RAKE|HOE|TROWEL|AXE|HATCHET|LADDER|TOOLBOX|NAIL|BOLT|NUT|WASHER|ANVIL|WHEELBARROW|"
     "PULLEY|WEDGE|SPANNER|ALLEN KEY|STAPLER|UTILITY KNIFE|PICKAXE"},
    {"vehicles", "Vehicles",
     "TRUCK|BUS|TAXI|TRAIN|TRAM|SUBWAY|BICYCLE|SCOOTER|MOTORCYCLE|TRACTOR|BULLDOZER|CRANE|FORKLIFT|"
     "AMBULANCE|FIRE ENGINE|POLICE CAR|AIRPLANE|HELICOPTER|GLIDER|BLIMP|ROCKET|SAILBOAT|CANOE|KAYAK|FERRY|"
     "YACHT|SUBMARINE|TUGBOAT|SLED|SNOWMOBILE|WAGON|CARRIAGE|SKATEBOARD|UNICYCLE|MINIVAN|PICKUP"},
    {"dinosaurs", "Dinosaurs",
     "TYRANNOSAURUS|TRICERATOPS|STEGOSAURUS|VELOCIRAPTOR|BRACHIOSAURUS|DIPLODOCUS|ANKYLOSAURUS|PTERODACTYL|"
     "SPINOSAURUS|ALLOSAURUS|IGUANODON|PARASAUROLOPHUS|APATOSAURUS|COMPSOGNATHUS|GALLIMIMUS|MICRORAPTOR|"
     "FOSSIL|BONES|EXTINCT|JURASSIC|TRIASSIC|CRETACEOUS|CLAW|TOOTH|EGG|NEST|HERBIVORE|CARNIVORE|PREDATOR|"
     "METEOR|SKELETON|AMBER|PALEONTOLOGIST|DIG|SCALES|TAIL"},
    {"rocks", "Rocks & Minerals",
     "GRANITE|BASALT|MARBLE|SLATE|SHALE|LIMESTONE|SANDSTONE|QUARTZ|FELDSPAR|MICA|GYPSUM|CALCITE|TALC|"
     "OBSIDIAN|PUMICE|FLINT|JASPER|AGATE|OPAL|GARNET|AMETHYST|TOPAZ|JADE|DIAMOND|RUBY|EMERALD|GRAPHITE|"
     "PYRITE|HEMATITE|MAGNETITE|COPPER|SILVER|GOLD|CRYSTAL|GEODE|FOSSIL|MAGMA|LAVA|IGNEOUS|SEDIMENTARY|"
     "METAMORPHIC"},
    {"jobs", "Jobs",
     "TEACHER|DOCTOR|NURSE|FARMER|BAKER|CHEF|PILOT|SAILOR|FIREFIGHTER|POLICE|DENTIST|VETERINARIAN|ENGINEER|"
     "SCIENTIST|ARTIST|WRITER|LIBRARIAN|CARPENTER|PLUMBER|ELECTRICIAN|MECHANIC|PAINTER|GARDENER|TAILOR|"
     "BARBER|CASHIER|BANKER|LAWYER|JUDGE|ARCHITECT|ASTRONAUT|MUSICIAN|PHOTOGRAPHER|DRIVER|RANGER|COACH|"
     "PHARMACIST|ACCOUNTANT"},
    {"clothing", "Clothing",
     "SHIRT|PANTS|JEANS|DRESS|SKIRT|SWEATER|JACKET|HOODIE|VEST|SCARF|GLOVES|MITTENS|HAT|CAP|BEANIE|SOCKS|"
     "SHOES|BOOTS|SANDALS|SLIPPERS|PAJAMAS|SHORTS|BELT|TIE|BLOUSE|OVERALLS|RAINCOAT|PARKA|POCKET|BUTTON|"
     "ZIPPER|COLLAR|SLEEVE|UNIFORM|TUXEDO|APRON"},
    {"farm", "Farm",
     "BARN|SILO|TRACTOR|PLOW|HARVEST|HAY|COW|CHICKEN|ROOSTER|SHEEP|GOAT|HORSE|DUCK|GOOSE|TURKEY|PONY|CALF|"
     "LAMB|PIGLET|FARMER|FIELD|CROPS|WHEAT|CORN|OATS|BARLEY|ORCHARD|PASTURE|FENCE|GATE|STABLE|TROUGH|"
     "SCARECROW|EGGS|MILK|PUMPKIN|GARDEN|WEATHERVANE|WINDMILL"},
    {"winter", "Winter",
     "SNOWMAN|ICICLE|FROST|BLIZZARD|SLED|SKATES|SKIS|MITTENS|SCARF|BOOTS|COCOA|FIREPLACE|BLANKET|CHIMNEY|"
     "PINE CONE|SNOWBALL|IGLOO|SNOWSHOE|TOBOGGAN|FLURRY|SLEET|PENGUIN|POLAR BEAR|HIBERNATE|SOLSTICE|CANDLE|"
     "QUILT|SWEATER|EARMUFFS|WOOL|FREEZING|CHILLY|SHOVEL|SNOWPLOW|ICE RINK"},
    {"science", "Science",
     "ATOM|MOLECULE|CELL|ENERGY|FORCE|GRAVITY|MAGNET|ELECTRON|PROTON|NEUTRON|NUCLEUS|OXYGEN|HYDROGEN|"
     "CARBON|ELEMENT|COMPOUND|MIXTURE|SOLUTION|EXPERIMENT|HYPOTHESIS|THEORY|MICROSCOPE|BEAKER|FLASK|LAB|"
     "DATA|OBSERVE|MEASURE|FOSSIL|GENE|DNA|VELOCITY|FRICTION|PHYSICS|BIOLOGY|CHEMISTRY|GEOLOGY|ASTRONOMY"},
    {"books", "Books & Reading",
     "NOVEL|CHAPTER|PAGE|AUTHOR|TITLE|COVER|SPINE|PLOT|CHARACTER|HERO|VILLAIN|SETTING|POETRY|POEM|STORY|"
     "FABLE|MYTH|LEGEND|MYSTERY|FANTASY|BIOGRAPHY|DIARY|JOURNAL|LIBRARY|SHELF|BOOKMARK|INDEX|GLOSSARY|"
     "PREFACE|EPILOGUE|PROLOGUE|PARAGRAPH|SENTENCE|NARRATOR|READER|ATLAS|DICTIONARY|FAIRY TALE"},
};

constexpr size_t THEME_COUNT = sizeof(THEMES) / sizeof(THEMES[0]);

}  // namespace

size_t builtinThemeCount() { return THEME_COUNT; }

const BuiltinTheme& builtinTheme(const size_t index) { return THEMES[index < THEME_COUNT ? index : 0]; }

int findBuiltinTheme(const char* key) {
  if (!key) return -1;
  for (size_t i = 0; i < THEME_COUNT; i++) {
    if (std::strcmp(THEMES[i].key, key) == 0) return static_cast<int>(i);
  }
  return -1;
}

}  // namespace ws
