#!/usr/bin/env python3
"""Draw the Day card's big day-of-month numerals and write them as a 1-bit header.

The built-in fonts stop at 18 pt; magnifying one of their glyphs 3-4x leaves steps on every
curve. These digits are rendered from the repository's own Noto Sans Bold outline
(lib/EpdFont/builtinFonts/source/NotoSans, SIL Open Font License) at their final size,
supersampled 8x and thresholded once, so the edges are as clean as the panel allows.

    python3 scripts/gen_card_digits.py
    ./bin/clang-format-fix -g      # the header is checked in clang-formatted

Output (checked in): src/images/CardDigits.h - two sizes of 0-9. Each digit is stored as its
ink box (row-major, MSB first, 1 = ink, rows padded to whole bytes) with its left bearing inside
the (tabular) advance, all digits of a size sharing one height, top = the digits' top.
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_PATH = os.path.join(ROOT, "lib", "EpdFont", "builtinFonts", "source", "NotoSans", "NotoSans-Bold.ttf")
HEADER_PATH = os.path.join(ROOT, "src", "images", "CardDigits.h")
SS = 8  # supersampling factor

# (name, digit height in px). The heights match the Day card's layout: 124 px alone, 94 px when
# the legal-light band needs the room.
SIZES = [("Large", 124), ("Medium", 94)]


def font_for_height(target):
    """The supersampled font whose digit '0' is target * SS px tall."""
    lo, hi = 10, 4000
    while lo < hi:
        mid = (lo + hi) // 2
        f = ImageFont.truetype(FONT_PATH, mid)
        b = f.getbbox("0")
        if b[3] - b[1] < target * SS:
            lo = mid + 1
        else:
            hi = mid
    return ImageFont.truetype(FONT_PATH, lo)


def render_set(height):
    font = font_for_height(height)
    # The digits' common vertical extent (lining figures: top of the tallest to the baseline).
    top = min(font.getbbox(str(d))[1] for d in range(10))
    bottom = max(font.getbbox(str(d))[3] for d in range(10))
    advance = max(font.getlength(str(d)) for d in range(10))
    adv_px = int(round(advance / SS))
    glyphs = []
    for d in range(10):
        big = Image.new("L", (int(advance) + 4 * SS, bottom - top), 0)
        ImageDraw.Draw(big).text((2 * SS, -top), str(d), font=font, fill=255)
        small = big.resize((big.width // SS, height), Image.LANCZOS)
        bw = small.point(lambda v: 255 if v >= 128 else 0)
        box = bw.getbbox()
        x0, x1 = box[0], box[2]
        ink = bw.crop((x0, 0, x1, height))
        left = x0 - 2  # the pen started 2 px in
        glyphs.append((left, ink))
    return adv_px, glyphs


def pack(ink):
    w, h = ink.size
    px = ink.load()
    out = []
    for y in range(h):
        for x in range(0, w, 8):
            byte = 0
            for b in range(8):
                if x + b < w and px[x + b, y] >= 128:
                    byte |= 1 << (7 - b)
            out.append(byte)
    return out


def main():
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Generated by scripts/gen_card_digits.py - do not edit; change the script and rerun it.",
        "// Noto Sans Bold digits (SIL Open Font License), 1 bit per pixel, 1 = ink, MSB first, each",
        "// digit its ink box row by row (rows padded to whole bytes).",
        "struct CardDigitFont {",
        "  int height;              // every digit's ink height; y = 0 is the digits' top",
        "  int advance;             // tabular: the same for every digit",
        "  const uint8_t* width;    // [10] ink width",
        "  const int8_t* left;      // [10] ink left edge from the pen position",
        "  const uint16_t* offset;  // [10] into bits",
        "  const uint8_t* bits;",
        "};",
        "",
    ]
    for name, height in SIZES:
        adv, glyphs = render_set(height)
        data, offsets, widths, lefts = [], [], [], []
        for left, ink in glyphs:
            offsets.append(len(data))
            widths.append(ink.size[0])
            lefts.append(left)
            data += pack(ink)
        assert len(data) < 65536
        lines.append(f"inline constexpr uint8_t CardDigits{name}Width[10] = {{{', '.join(map(str, widths))}}};")
        lines.append(f"inline constexpr int8_t CardDigits{name}Left[10] = {{{', '.join(map(str, lefts))}}};")
        lines.append(f"inline constexpr uint16_t CardDigits{name}Offset[10] = {{{', '.join(map(str, offsets))}}};")
        lines.append(f"inline constexpr uint8_t CardDigits{name}Bits[] = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{v:02X}" for v in data[i:i + 16]) + ",")
        lines.append("};")
        lines.append(
            f"inline constexpr CardDigitFont CARD_DIGITS_{name.upper()} = {{{height}, {adv}, CardDigits{name}Width, "
            f"CardDigits{name}Left, CardDigits{name}Offset, CardDigits{name}Bits}};")
        lines.append("")
        print(f"{name}: height {height}, advance {adv}, {len(data)} bytes")
    with open(HEADER_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {HEADER_PATH}")


if __name__ == "__main__":
    main()
