#!/usr/bin/env python3
"""Generate test/sleep_card_sky/SkyVectors.h: PyEphem ground truth for the Sky card's planets.

src/sleepcards/SkyPlanets.cpp computes where Venus, Mars, Jupiter and Saturn are with a low-precision
method (Paul Schlyter's "How to compute planetary positions": mean orbital elements, Kepler's
equation, the largest Jupiter/Saturn perturbations) and finds their rise, transit and set by
iteration. A wrong planet looks as plausible as a right one, so the host test
(test/sleep_card_sky/SleepCardSkyTest.cpp) replays what PyEphem says for the same instants and
places: public test coordinates only (city centres), a spread of dates over 2026-2030.

  * positions: topocentric apparent altitude/azimuth with no refraction (pressure 0), and the
    apparent geocentric RA/Dec of date (g_ra/g_dec).
  * events: next_rising / next_setting / next_transit and previous_rising / previous_setting from
    each instant, horizon -0:34, pressure 0 (the almanac definition, as lib/Almanac uses for the sun
    and the moon). 0 = PyEphem found none (the planet is circumpolar or never up there).
  * conditioning: the altitude at the upper and the lower culmination nearest the instant, so the
    test can skip passes that only graze the horizon (a rise time is ill-conditioned there: a tiny
    declination error moves it by many minutes).

    pip install --user ephem      # 4.2.1 used for the checked-in header
    python3 scripts/gen_sky_vectors.py
"""
import argparse
import math
import os
import sys

try:
    import ephem
except ImportError as e:
    sys.exit("need ephem: pip install --user ephem (%s)" % e)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EPOCH = ephem.Date("1970/1/1 00:00:00")

# Public places only (the same test coordinates as scripts/gen_almanac_vectors.py).
PLACES = [
    ("seattle", 47.6062, -122.3321),
    ("fairbanks", 64.8378, -147.7164),
    ("quito", -0.1807, -78.4678),
    ("hobart", -42.8821, 147.3272),
]

PLANETS = [("venus", ephem.Venus), ("mars", ephem.Mars), ("jupiter", ephem.Jupiter), ("saturn", ephem.Saturn)]

# A spread of instants over 2026-2030 (UTC), at two times of day so both evening and morning skies
# are sampled somewhere on the globe.
DATES = [
    "2026/01/15", "2026/06/01", "2026/11/03", "2027/03/20", "2027/09/09", "2028/02/14",
    "2028/07/30", "2029/01/05", "2029/05/25", "2029/12/12", "2030/04/18", "2030/10/01",
]
HOURS = [4, 16]


def unix(d):
    return int(round((float(d) - float(EPOCH)) * 86400.0))


def edate(u):
    return ephem.Date(EPOCH + u / 86400.0)


def observer(lat, lon, t):
    o = ephem.Observer()
    o.lat, o.lon = str(lat), str(lon)
    o.elevation = 0
    o.pressure = 0
    o.horizon = "-0:34"
    o.date = edate(t)
    return o


def event(fn):
    try:
        return unix(fn())
    except (ephem.NeverUpError, ephem.AlwaysUpError, ephem.CircumpolarError):
        return 0


def alt_at(body_cls, lat, lon, t):
    o = observer(lat, lon, t)
    b = body_cls()
    b.compute(o)
    return math.degrees(b.alt)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--header", default=os.path.join(ROOT, "test", "sleep_card_sky", "SkyVectors.h"))
    a = ap.parse_args()

    rows = []
    for date in DATES:
        for hour in HOURS:
            t = unix(ephem.Date(date)) + hour * 3600
            for place, lat, lon in PLACES:
                for pi, (pname, cls) in enumerate(PLANETS):
                    o = observer(lat, lon, t)
                    b = cls()
                    b.compute(o)
                    alt, az = math.degrees(b.alt), math.degrees(b.az)
                    gra, gdec = math.degrees(b.g_ra), math.degrees(b.g_dec)
                    ev = {}
                    for key, name in (("nrise", "next_rising"), ("nset", "next_setting"),
                                      ("ntransit", "next_transit"), ("prise", "previous_rising"),
                                      ("pset", "previous_setting")):
                        o = observer(lat, lon, t)
                        ev[key] = event(lambda: getattr(o, name)(cls()))
                    # culminations nearest t: the next transit and the antitransit nearest it
                    o = observer(lat, lon, t)
                    tr = unix(o.next_transit(cls()))
                    o = observer(lat, lon, tr)
                    anti = unix(o.next_antitransit(cls()))
                    upper = alt_at(cls, lat, lon, tr)
                    lower = alt_at(cls, lat, lon, anti)
                    rows.append((place, lat, lon, t, pi, alt, az, gra, gdec, ev["nrise"], ev["nset"],
                                 ev["ntransit"], ev["prise"], ev["pset"], upper, lower))

    h = ["// GENERATED by scripts/gen_sky_vectors.py - do not edit. PyEphem %s." % ephem.__version__,
         "// Public test coordinates only. t and events are UNIX seconds; an event of 0 = PyEphem found none.",
         "// planet: 0 Venus, 1 Mars, 2 Jupiter, 3 Saturn. alt/az topocentric, no refraction; ra/dec",
         "// apparent geocentric of date. upper/lower = altitude at the culminations nearest t.",
         "#pragma once", "#include <cstdint>", "",
         "struct SkyVec {", "  const char* place;", "  double lat, lon;", "  int64_t t;", "  int planet;",
         "  double alt, az, ra, dec;", "  int64_t nextRise, nextSet, nextTransit, prevRise, prevSet;",
         "  double upperAlt, lowerAlt;", "};", "",
         "static const SkyVec SKY_VECTORS[] = {"]
    for r in rows:
        h.append('    {"%s", %.4f, %.4f, %d, %d, %.5f, %.5f, %.5f, %.5f, %d, %d, %d, %d, %d, %.4f, %.4f},' % r)
    h.append("};")
    with open(a.header, "w") as f:
        f.write("\n".join(h) + "\n")
    print("rows=%d -> %s" % (len(rows), a.header))


if __name__ == "__main__":
    main()
