#pragma once

// Crossword built-in puzzles (flash). The data, CwBuiltinData.cpp, is GENERATED by
// scripts/crossword/gen_builtin.py from scripts/crossword/builtin.txt; each puzzle's text is its
// block of that file, parsed on load by parseTextPuzzle (the same parser the host tests run on
// every built-in). Titles and clues are English CONTENT, not UI strings: no tr().

#include <cstddef>
#include <cstdint>

namespace cw {

struct BuiltinPuzzle {
  const char* id;     // stable: "mini-001" (its sourceKey is "builtin:mini-001")
  const char* title;  // for the picker without parsing
  uint8_t w;
  uint8_t h;
  uint32_t fnv;      // puzzleFnv of its solution (the tests check it)
  const char* text;  // the block, in the built-in text format
};

size_t builtinCount();
const BuiltinPuzzle& builtinPuzzle(size_t index);
// Index of the built-in with this id ("mini-001", not "builtin:mini-001"), or -1.
int findBuiltin(const char* id);

}  // namespace cw
